#!/bin/bash


echo You are on:
hostname -f
echo You are about to replace all the content on remote servers with files from this server that you are on
cat /etc/acsync.directories
echo
echo
echo You have 10 seconds to cancel with CTRL+C
for i in {10..1}; do 
  echo -n "$i .. "
  sleep 1;
done 
echo 
echo 'Going to do it now!'


LOCAL_IP_REGEX=$(echo $(ip a | awk '{ if( $1 == "inet") print $2 }' | grep -E -o "([0-9]{1,3}[\.]){3}[0-9]{1,3}") | sed 's/ /|/g')

# Sync up all the included syncable directories. 
cat /etc/acsync.directories | grep -vE $LOCAL_IP_REGEX | while read SYNC_DIR; do
  cat /etc/acsync.servers | grep -vE $LOCAL_IP_REGEX | while read REMOTE_IP; do
    echo rsync -e "ssh -o StrictHostKeyChecking=no" --temp-dir=/tmp --delete -avz $SYNC_DIR/ $REMOTE_IP:$SYNC_DIR
    rsync -e "ssh -o StrictHostKeyChecking=no" --temp-dir=/tmp --delete -avz $SYNC_DIR/ $REMOTE_IP:$SYNC_DIR
  done
done
