#!/bin/bash

LOCAL_IP_REGEX=$(echo $(ip a | awk '{ if( $1 == "inet") print $2 }' | grep -E -o "([0-9]{1,3}[\.]){3}[0-9]{1,3}") | sed 's/ /|/g')


echo You are on:
hostname -f


if [ "$1" == "" ]; then
  echo All the remote servers in this list:
  cat /etc/acsync.servers | grep -vE $LOCAL_IP_REGEX
  echo
  echo are about to have these directories nuked and initialized from this server:
  cat /etc/acsync.directories
else
  echo You are about to inialized $1 with the content of these directories:
  cat /etc/acsync.directories
fi

echo
echo
echo You have 10 seconds to cancel with CTRL+C
for i in {10..1}; do 
  echo -n "$i .. "
  sleep 1;
done 
echo 
echo 'Going to do it now!'


# Sync up all the included syncable directories. 
cat /etc/acsync.directories | while read SYNC_DIR; do


  if [ "$1" == "" ]; then
    cat /etc/acsync.servers | grep -vE $LOCAL_IP_REGEX | while read REMOTE_IP; do
      echo rsync -e "ssh -o StrictHostKeyChecking=no" --temp-dir=/tmp --delete -avz $SYNC_DIR/ $REMOTE_IP:$SYNC_DIR
      rsync -e "ssh -o StrictHostKeyChecking=no" --temp-dir=/tmp --delete -avz $SYNC_DIR/ $REMOTE_IP:$SYNC_DIR
    done
  else
      REMOTE_IP=$1
      echo rsync -e "ssh -o StrictHostKeyChecking=no" --temp-dir=/tmp --delete -avz $SYNC_DIR/ $REMOTE_IP:$SYNC_DIR
      rsync -e "ssh -o StrictHostKeyChecking=no" --temp-dir=/tmp --delete -avz $SYNC_DIR/ $REMOTE_IP:$SYNC_DIR
  fi

done
